export const About = {
    double: false,
    id: 'about',
    altBg: false,
    altText: true,
    altTextDescription: true,
    intro: "Get to know more...",
    h1: "...About Us",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quidem nemo voluptatem magni iusto omnis? Fuga, inventore a praesentium, voluptates ipsum recusandae ea officia itaque aperiam asperiores numquam alias explicabo!",
    buttonLabel: "Reserve a Seat",
    imgPosition: false,
    img: require('../../images/interior1.jpg').default,
    alt: "Restaurant interior",
    dark: true,
    primary: true,
    altText: false,
}

export const Team = {
    double: true,
	id: "team",
	altBg: true,
	altText: false,
	altTextDesc: false,
	intro: "Meet the...",
	h1: "...Chefs",
	description:
		"Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quidem nemo voluptatem magni iusto omnis? Fuga, inventore a praesentium, voluptates ipsum recusandae ea officia itaque aperiam asperiores numquam alias explicabo!",
	buttonLabel: "Come Visit Us",
	imgPosition: true,
	img: require("../../images/food2.jpg").default,
	alt: "Restaurant interior",
	dark: false,
	primary: false,
	altText: true,
};